// The templates are generated by bicep IaC generator

param location string = resourceGroup().location
param functionappAzurefunctions-d462c10c-0ab9-4ce5-961a-27ea4e215e7bName string = 'azurefunctions-d462c10c-0ab9-4ce5-961a-27ea4e215e7b${uniqueString(resourceGroup().id)}'
param botAzurebotservice-5e8690a2-2f9a-4b35-9ea7-a423d9f59dcdName string = 'azurebotservice-5e8690a2-2f9a-4b35-9ea7-a423d9f59dcd${uniqueString(resourceGroup().id)}'
param botAadAppClientId string
param functionAppPlanName string = 'azurefunctions-d462c10c-0ab9-4ce5-961a-27ea4e215e7b${uniqueString(resourceGroup().id)}'
param storageAccountFuncdepName string = 'funcdep${uniqueString(resourceGroup().id)}'


// Deploy an Azure Functions hosting Plan

module functionAppPlan 'functionappplan.bicep' = {
	name: 'fucntionapp-plan-deployment'
	params: {
		location: location
		name: functionAppPlanName
	}
}
var functionAppPlanId = functionAppPlan.outputs.id

// Deploy an Azure Storage Account

module storageAccountFuncdepDeployment 'storageaccount.bicep' = {
	name: 'storage-account-funcdep-deployment'
	params: {
		location: location
		name: storageAccountFuncdepName 
	}
}

// Deploy an Azure Function App

module functionappAzurefunctionsD462c10c0ab94ce5961a27ea4e215e7bDeployment 'functionapp.bicep' = {
	name: 'function-app-azurefunctions-d462c10c-0ab9-4ce5-961a-27ea4e215e7b-deployment'
	params: {
		location: location
		name: functionappAzurefunctions-d462c10c-0ab9-4ce5-961a-27ea4e215e7bName
		storageAccountName: storageAccountFuncdepName
		functionAppPlanId: functionAppPlanId 
	}
	dependsOn: [
		functionAppPlan
		storageAccountFuncdepDeployment
	]
}

// Deploy an Azure Bot Service

module botAzurebotservice5e8690a22f9a4b359ea7A423d9f59dcdDeployment 'botservice.bicep' = {
	name: 'bot-azurebotservice-5e8690a2-2f9a-4b35-9ea7-a423d9f59dcd-deployment'
	params: {
		name: botAzurebotservice-5e8690a2-2f9a-4b35-9ea7-a423d9f59dcdName
		botAadAppClientId: botAadAppClientId 
	}
}



output functionappAzurefunctions-d462c10c-0ab9-4ce5-961a-27ea4e215e7bId string = functionappAzurefunctionsD462c10c0ab94ce5961a27ea4e215e7bDeployment.outputs.id
output botAzurebotservice-5e8690a2-2f9a-4b35-9ea7-a423d9f59dcdId string = botAzurebotservice5e8690a22f9a4b359ea7A423d9f59dcdDeployment.outputs.id
output storageAccountFuncdepId string = storageAccountFuncdepDeployment.outputs.id